### ISSUE TITLE
Traceback with Markdown Extra when beginning with an HTML comment

### ISSUE THREAD

**Issue by jpfleury** [Python-Markdown/markdown#108]
Say the following code:

```
import markdown

text = """
<!-- HTML comment -->
**Hello** world.
"""

print markdown.markdown(text, ['extra'])
```

It will fail with the following traceback:

```
Traceback (most recent call last):
  File "sample.py", line 8, in <module>
    print markdown.markdown(text, ['extra'])
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/__init__.py", line 396, in markdown
    return md.convert(text)
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/__init__.py", line 280, in convert
    self.lines = prep.run(self.lines)
  File "/home/nom/.local/lib/python2.7/site-packages/markdown/preprocessors.py", line 175, in run
    if self.markdown_in_raw and 'markdown' in attrs.keys():
AttributeError: 'tuple' object has no attribute 'keys'
```

I can reproduce this bug with versions 2.1.0 and 2.2.0-alpha.

**Comment by jpfleury** [comment]
Note that the following will also fail:

```
import markdown

text = """
<p>Paragraph</p><!-- HTML comment -->
**Hello** world.
"""

print markdown.markdown(text, ['extra'])
```

**Comment by skurfer** [comment]
The return of #76?

**Comment by waylan** [comment]
I can't reproduce this in the latest code. I suspect this was fixed in #76 as @skurfer pointed out. Are you sure you are actually running 2.2.0?

``` python

>>> import markdown
>>> text = """
... <!-- HTML comment -->
... **Hello** world.
... """
>>> print markdown.markdown(text, extensions=['extra'])
<!-- HTML comment -->

<p><strong>Hello</strong> world.</p>
>>> markdown.version
'2.2.0'
```

**Comment by waylan** [comment]
And just to be sure, this works fine as well:

``` python

>>> text = """
... <p>Paragraph</p><!-- HTML comment -->
... **Hello** world.
... """
>>> print markdown.markdown(text, extensions=['extra'])
<p>Paragraph</p>

<!-- HTML comment -->

<p><strong>Hello</strong> world.</p>
```

**Comment by jpfleury** [comment]
I've just tested with 4dd11880, and you're right, no bug. Thanks.
