### ISSUE TITLE
Fix for compatibility with Python 3.5

### ISSUE THREAD

**Issue by mDuo13** [Python-Markdown/markdown#1085]
As of Dec. 1, [importlib-metadata](https://pypi.org/project/importlib-metadata/#history) v3.0+ doesn't support Python 3.0 through 3.5. I found this out the hard way on an Ubuntu 16.04 LTS server (still not end-of-life!) when I got the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/markdown/util.py", line 32, in <module>
    from importlib import metadata
ImportError: cannot import name 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  (...my code here...)
  File "/usr/local/lib/python3.5/dist-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "/usr/local/lib/python3.5/dist-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/usr/local/lib/python3.5/dist-packages/markdown/util.py", line 35, in <module>
    import importlib_metadata as metadata
  File "/usr/local/lib/python3.5/dist-packages/importlib_metadata/__init__.py", line 43, in <module>
    class PackageNotFoundError(ModuleNotFoundError):
NameError: name 'ModuleNotFoundError' is not defined
```

I was able to work around the problem by manually doing the following:

```
pip3 install importlib-metadata==2.1.1
```

I'm not sure if there's something that can be done in the Python-Markdown source to fix this, but I wanted to at least report the issue and my workaround here in case someone else encounters the same issue.

**Comment by waylan** [comment]
Python dropped support for version 3.5 on 2020-09-13 and we dropped support with the release of version 3.3 on 2020-10-06. As we don't support Python 3.5, this is not an issue.
