### ISSUE TITLE
Build failure with Python 2.5

### ISSUE THREAD

**Issue by Arfrever** [Python-Markdown/markdown#113]
`docs/release-2.2.0.txt` says that Python 2.5 is still supported, but building with Python 2.5 fails.

```
$ python2.5 setup.py build
...
running build_docs
build/lib/markdown/odict.py:159: Warning: 'as' will become a reserved keyword in Python 2.6
Traceback (most recent call last):
  File "setup.py", line 208, in <module>
    setup(**data)
  File "/usr/lib64/python2.5/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.5/distutils/dist.py", line 974, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.5/distutils/dist.py", line 994, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.5/distutils/command/build.py", line 112, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.5/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.5/distutils/dist.py", line 994, in run_command
    cmd_obj.run()
  File "setup.py", line 125, in run
    import markdown
  File "build/lib/markdown/__init__.py", line 41, in <module>
    from preprocessors import build_preprocessors
  File "build/lib/markdown/preprocessors.py", line 11, in <module>
    import odict
  File "build/lib/markdown/odict.py", line 159
    except Exception as e:
                      ^
SyntaxError: invalid syntax
```

Please use `except Exception, e:` or drop support for Python 2.5.

Also please delete the following code in `setup.py`:

```
if sys.version[:3] < '2.5':
    data['install_requires'] = ['elementtree']
```

**Comment by waylan** [comment]
Fixed in 34cb4827da7eee2310ab285110cdadfdfbc85993
