### ISSUE TITLE
Convert doctests to Unittests

### ISSUE THREAD

**Issue by Arfrever** [Python-Markdown/markdown#114]
Python 2.6.8, 2.7.3, 3.1.5 and 3.2.3 contain optional randomization of hashes, which affects order of items in representation of dictionaries. Randomization of hashes is enabled by default in Python 3.3.

```
$ python2.7 -R run-tests.py
...
======================================================================
FAIL: Doctest: markdown.extensions.meta
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/doctest.py", line 2201, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for markdown.extensions.meta
  File "/tmp/Markdown-2.2.0/markdown/extensions/meta.py", line 2, in meta

----------------------------------------------------------------------
File "/tmp/Markdown-2.2.0/markdown/extensions/meta.py", line 22, in markdown.extensions.meta
Failed example:
    print md.Meta
Expected:
    {u'blank_data': [u''], u'author': [u'Waylan Limberg', u'John Doe'], u'title': [u'A Test Doc.']}
Got:
    {u'author': [u'Waylan Limberg', u'John Doe'], u'blank_data': [u''], u'title': [u'A Test Doc.']}


----------------------------------------------------------------------
```

**Comment by waylan** [comment]
Yeah, some of the doctests fail in Python 3.x. The `u'...'` sting formating also trips up doctests in Python 3.x. Perhaps someday when I have the time I'll convert all doctests (only found in extensions IIRC) to unittests. I've updated the title to reflect that. Of course, patches (pull requests) are welcome.

**Comment by Arfrever** [comment]
The following patch fixes originally reported problem with hash randomization enabled:

```
--- markdown/extensions/meta.py
+++ markdown/extensions/meta.py
@@ -19,8 +19,8 @@ Basic Usage:
     >>> md = markdown.Markdown(['meta'])
     >>> print md.convert(text)
     <p>The body. This is paragraph one.</p>
-    >>> print md.Meta
-    {u'blank_data': [u''], u'author': [u'Waylan Limberg', u'John Doe'], u'title': [u'A Test Doc.']}
+    >>> md.Meta == {u'author': [u'Waylan Limberg', u'John Doe'], u'blank_data': [u''], u'title': [u'A Test Doc.']}
+    True

 Make sure text without Meta Data still works (markdown < 1.6b returns a <p>).

```
