### ISSUE TITLE
cannot import name 'etree' from 'markdown.util'

### ISSUE THREAD

**Issue by Alexey-T** [Python-Markdown/markdown#1284]
- Markdown 3.4.1 from PyPI
- py-gfm 1.0.2 from PyPI
- pygments from PyPI

Crash in CudaText plugin "Markdown Preview" (not published this version yet) with all new Py modules from PyPI. On Xubuntu 20 x64.
```
Python 3.8.10
Startup: 400ms, plugins: 0ms ()
Init: cuda_breadcrumbs
Init: cuda_git_status
Init: cuda_runner
Init: cuda_hilite_occurrences
Init: cuda_markdown_preview
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/__init__.py", line 9, in <module>
    from .cuda_markdown_options import ext
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/cuda_markdown_options.py", line 1, in <module>
    from mdx_gfm import GithubFlavoredMarkdownExtension
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/mdx_gfm/__init__.py", line 30, in <module>
    from mdx_partial_gfm import PartialGithubFlavoredMarkdownExtension
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/mdx_partial_gfm/__init__.py", line 30, in <module>
    import gfm
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/gfm/__init__.py", line 15, in <module>
    from gfm import tasklist
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/gfm/tasklist.py", line 183, in <module>
    from markdown.util import etree
ImportError: cannot import name 'etree' from 'markdown.util' (/home/user/.config/cudatext/py/cuda_markdown_preview/markdown/util.py)
ERROR: Exception in CudaText for cuda_markdown_preview.run: ImportError: cannot import name 'etree' from 'markdown.util' (/home/user/.config/cudatext/py/cuda_markdown_preview/markdown/util.py)
```

What did i install wrong?

**Comment by Alexey-T** [comment]
Updated CudaText plugin is here (it crashes with the error shown above)
https://github.com/CudaText-addons/cuda_markdown_preview
branch 'new_py_libs'

**Comment by mitya57** [comment]
`cuda_markdown_preview` is using API which was [deprecated][1] in Python-Markdown 3.2 and [removed][2] in 3.4.

`from markdown.util import etree` should be replaced with `import xml.etree.ElementTree as etree`.

[1]: https://python-markdown.github.io/change_log/release-3.2/#markdownutiletree-deprecated
[2]: https://python-markdown.github.io/change_log/release-3.4/#previously-deprecated-objects-have-been-removed
