### ISSUE TITLE
ModuleNotFoundError: No module named 'fenced_code'

### ISSUE THREAD

**Issue by Alexey-T** [Python-Markdown/markdown#1285]
To CudaText plugin
https://github.com/CudaText-addons/cuda_markdown_preview/tree/new_py_libs
i added more required libs

- zipp
- importlib_metadata
- fenced_code_plus

from PyPI.
now I got error SUBJ and I cannot find this lib: fenced_code.

**Comment by Alexey-T** [comment]
```
Python 3.8.10
Startup: 350ms, plugins: 0ms ()
Init: cuda_breadcrumbs
Init: cuda_git_status
Init: cuda_runner
Init: cuda_markdown_preview
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/__init__.py", line 10, in <module>
    md = markdown.Markdown(extensions=ext)
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/markdown/core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/markdown/core.py", line 125, in registerExtensions
    ext.extendMarkdown(self)
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/markdown/extensions/extra.py", line 54, in extendMarkdown
    md.registerExtensions(extensions, self.config)
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/markdown/core.py", line 123, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/user/.config/cudatext/py/cuda_markdown_preview/markdown/core.py", line 162, in build_extension
    module = importlib.import_module(ext_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'fenced_code'
ERROR: Exception in CudaText for cuda_markdown_preview.run: ModuleNotFoundError: No module named 'fenced_code'
```

**Comment by Alexey-T** [comment]
Found 'fenced_code' in 'extensions' sub dir - but I see that it cannot be found by main py code! something is wrong with `sys.path` or importlib?

**Comment by mitya57** [comment]
Short aliases for extensions are available only if Python-Markdown is properly installed, and its entry points are visible to `importlib.metadata`.

If you simply copied `markdown` directory to your own project, you should use full names, e.g. `markdown.extensions.fenced_code`.

**Comment by Alexey-T** [comment]
do you mean I must add prefixes here in extra.py ?
```
extensions = [
    'fenced_code',
    'footnotes',
    'attr_list',
    'def_list',
    'tables',
    'abbr',
    'md_in_html'
]
```

did this, seems working now.

**Comment by mitya57** [comment]
Yes. Or you can import extension class and pass instance of it. See the docs for details:
https://python-markdown.github.io/reference/#extensions
