### ISSUE TITLE
Failed to load codehilite in 2.2.1

### ISSUE THREAD

**Issue by beala** [Python-Markdown/markdown#162]
Upgrading from 2.2.0 to 2.2.1 seems to have broken support for codehilite.

Here is the error message:

```
 Traceback (most recent call last):
  File "paleo.py", line 42, in <module>
    post_list = stage_obj.process(post_list)
  File "/Users/beala/Dropbox/Programming/Python/paleoblogger/rssgenstage.py", line 22, in process
    post_rss.append(self._make_rss_item(post))
  File "/Users/beala/Dropbox/Programming/Python/paleoblogger/rssgenstage.py", line 42, in _make_rss_item
    desc = self._process_desc(post)
  File "/Users/beala/Dropbox/Programming/Python/paleoblogger/rssgenstage.py", line 62, in _process_desc
    ['fenced_code', ' codehilite'])
  File "/Users/beala/.virtualenvs/lamark/lib/python2.7/site-packages/markdown/__init__.py", line 418, in markdown
    md = Markdown(*args, **kwargs)
  File "/Users/beala/.virtualenvs/lamark/lib/python2.7/site-packages/markdown/__init__.py", line 139, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/Users/beala/.virtualenvs/lamark/lib/python2.7/site-packages/markdown/__init__.py", line 165, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, []))
  File "/Users/beala/.virtualenvs/lamark/lib/python2.7/site-packages/markdown/__init__.py", line 203, in build_extension
    module = __import__(module_name_old_style)
ImportError: Failed loading extension ' codehilite' from 'markdown.extensions. codehilite' or 'mdx_ codehilite'
```

And here is the line producing that message:

```
        desc_tmp = markdown.markdown(
                desc_tmp,
                ['fenced_code', ' codehilite'])
```

I looked around pypi for an mdx_codehilite package, but didn't see one.

Thanks!

**Comment by waylan** [comment]
You need to remove the space from the front of the string your passing in.
It's `'codehite'` not `' codehilite'`. Go back and look more closely at the
error message again. You will see that it tried to load from a few
different locations, but they all have a space in them - so, naturally,
none of those files exist.

Waylan Limberg
waylan@gmail.com

**Comment by beala** [comment]
Ah right you are. I didn't look very closely at my code since it worked with previous versions. Thanks! :)

**Comment by Ex-Muslims** [comment]
This works for me:

```
import markdown
from markdown.extensions.fenced_code import FencedCodeExtension
from markdown.extensions.codehilite import CodeHiliteExtension
from django import template
from django.template.defaultfilters import stringfilter

register = template.Library()

@register.filter
@stringfilter
def convert_markdown(value):
    return markdown.markdown(value, extensions=[FencedCodeExtension(), CodeHiliteExtension()])
```
