### ISSUE TITLE
Test failure with Python 3.3

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#194]
When running the test suite under Python 3.3, I get:

```
ERROR: TestSyntax: "extensions/attr_list"
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mandriver/Python-Markdown/build/lib/tests/__init__.py", line 95, in __call__
    output = markdown.markdown(input, **get_args(file, config))
  File "/home/mandriver/Python-Markdown/build/lib/markdown/__init__.py", line 410, in markdown
    return md.convert(text)
  File "/home/mandriver/Python-Markdown/build/lib/markdown/__init__.py", line 299, in convert
    output = self.serializer(root)
  File "/home/mandriver/Python-Markdown/build/lib/markdown/serializers.py", line 277, in to_xhtml_string
    return _write_html(ElementTree(element).getroot(), format="xhtml")
  File "/home/mandriver/Python-Markdown/build/lib/markdown/serializers.py", line 197, in _write_html
    qnames, namespaces = _namespaces(root, default_namespace)
  File "/home/mandriver/Python-Markdown/build/lib/markdown/serializers.py", line 265, in _namespaces
    add_qname(key)
  File "/home/mandriver/Python-Markdown/build/lib/markdown/serializers.py", line 223, in add_qname
    uri, tag = qname[1:].split("}", 1)
ValueError: need more than 1 value to unpack
```

After some investigation, I found out that the corresponding ElementTree element is

```
[('{:', '{:'), ('id', 'hash5')]
```

while with Python 3.2 it is

```
[('_:', '{:'), ('id', 'hash5')]
```

**Comment by waylan** [comment]
This looks suspiciously like Issue #164. Are you running the latest code including the second patch to that issue?

**Comment by mitya57** [comment]
Yes, it is the latest `git pull`-ed code.

**Comment by waylan** [comment]
This is weird:

``` python
import markdown
md = markdown.Markdown(extensions=['attr_list'])
md.treeprocessors['attr_list'].sanitize_name('{:')
```

In Python =< 3.2 the above returns: `"_:"` (as it should)
But in Python 3.3 we get: `"{:"`

For some strange reason the [NAME_RE](https://github.com/waylan/Python-Markdown/blob/4ff74e33a48a8c4e101d2f5e259d7b911c03d9f9/markdown/extensions/attr_list.py#L70) regex doesn't work in Python 3.3 and so attribute names are not being sanitized properly.
