### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by Arfrever** [Python-Markdown/markdown#203]
Markdown 2.3 introduced invalid syntax in some files, which happens to work in CPython, but does not work in Jython (2.7) or PyPy. str literals should not be used between imports from `__future__`. See http://bugs.python.org/issue17434.

```
$ jython2.7 -c 'import markdown'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "markdown/__init__.py", line 34
SyntaxError: from __future__ imports must occur at the beginning of the file
```

Patch for Markdown (which also replaces a comment with docstring in markdown/blockprocessors.py):

```
--- markdown/__init__.py
+++ markdown/__init__.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Python Markdown
 ===============
@@ -32,6 +31,7 @@ License: BSD (see LICENSE for details).
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from .__version__ import version, version_info
 import re
 import codecs
--- markdown/blockprocessors.py
+++ markdown/blockprocessors.py
@@ -1,17 +1,19 @@
-from __future__ import unicode_literals
-# CORE MARKDOWN BLOCKPARSER
-# ===========================================================================
-#
-# This parser handles basic parsing of Markdown blocks.  It doesn't concern itself
-# with inline elements such as **bold** or *italics*, but rather just catches 
-# blocks, lists, quotes, etc.
-#
-# The BlockParser is made up of a bunch of BlockProssors, each handling a 
-# different type of block. Extensions may add/replace/remove BlockProcessors
-# as they need to alter how markdown blocks are parsed.
+"""
+CORE MARKDOWN BLOCKPARSER
+===========================================================================
+
+This parser handles basic parsing of Markdown blocks.  It doesn't concern itself
+with inline elements such as **bold** or *italics*, but rather just catches
+blocks, lists, quotes, etc.
+
+The BlockParser is made up of a bunch of BlockProssors, each handling a
+different type of block. Extensions may add/replace/remove BlockProcessors
+as they need to alter how markdown blocks are parsed.
+"""

 from __future__ import absolute_import
 from __future__ import division
+from __future__ import unicode_literals
 import logging
 import re
 from . import util
--- markdown/extensions/__init__.py
+++ markdown/extensions/__init__.py
@@ -1,9 +1,10 @@
-from __future__ import unicode_literals
 """
 Extensions
 -----------------------------------------------------------------------------
 """

+from __future__ import unicode_literals
+
 class Extension(object):
     """ Base class for extensions to subclass. """
     def __init__(self, configs = {}):
--- markdown/extensions/abbr.py
+++ markdown/extensions/abbr.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 '''
 Abbreviation Extension for Python-Markdown
 ==========================================
@@ -25,6 +24,7 @@ Copyright 2007-2008
 '''

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..preprocessors import Preprocessor
 from ..inlinepatterns import Pattern
--- markdown/extensions/admonition.py
+++ markdown/extensions/admonition.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Admonition extension for Python-Markdown
 ========================================
@@ -42,6 +41,7 @@ By [Tiago Serafim](http://www.tiagoserafim.com/).
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..blockprocessors import BlockProcessor
 from ..util import etree
--- markdown/extensions/attr_list.py
+++ markdown/extensions/attr_list.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Attribute List Extension for Python-Markdown
 ============================================
@@ -20,6 +19,7 @@ Dependencies:
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..treeprocessors import Treeprocessor
 from ..util import isBlockLevel
--- markdown/extensions/codehilite.py
+++ markdown/extensions/codehilite.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 CodeHilite Extension for Python-Markdown
 ========================================
@@ -20,6 +19,7 @@ Dependencies:
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..treeprocessors import Treeprocessor
 import warnings
--- markdown/extensions/def_list.py
+++ markdown/extensions/def_list.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Definition List Extension for Python-Markdown
 =============================================
@@ -20,6 +19,7 @@ Copyright 2008 - [Waylan Limberg](http://achinghead.com)
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..blockprocessors import BlockProcessor, ListIndentProcessor
 from ..util import etree
--- markdown/extensions/extra.py
+++ markdown/extensions/extra.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Python-Markdown Extra Extension
 ===============================
@@ -28,6 +27,7 @@ when you upgrade to any future version of Python-Markdown.
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension

 extensions = ['smart_strong',
--- markdown/extensions/fenced_code.py
+++ markdown/extensions/fenced_code.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Fenced Code Extension for Python Markdown
 =========================================
@@ -75,6 +74,7 @@ Dependencies:
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..preprocessors import Preprocessor
 from .codehilite import CodeHilite, CodeHiliteExtension
--- markdown/extensions/footnotes.py
+++ markdown/extensions/footnotes.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 ========================= FOOTNOTES =================================

@@ -25,6 +24,7 @@ Example:
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..preprocessors import Preprocessor
 from ..inlinepatterns import Pattern
--- markdown/extensions/headerid.py
+++ markdown/extensions/headerid.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 HeaderID Extension for Python-Markdown
 ======================================
@@ -76,6 +75,7 @@ Dependencies:
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..treeprocessors import Treeprocessor
 import re
--- markdown/extensions/meta.py
+++ markdown/extensions/meta.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Meta Data Extension for Python-Markdown
 =======================================
@@ -41,6 +40,7 @@ License: BSD (see ../LICENSE.md for details)
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..preprocessors import Preprocessor
 import re
--- markdown/extensions/nl2br.py
+++ markdown/extensions/nl2br.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 NL2BR Extension
 ===============
@@ -22,6 +21,7 @@ Dependencies:
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..inlinepatterns import SubstituteTagPattern

--- markdown/extensions/sane_lists.py
+++ markdown/extensions/sane_lists.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Sane List Extension for Python-Markdown
 =======================================
@@ -20,6 +19,7 @@ Copyright 2011 - [Waylan Limberg](http://achinghead.com)
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..blockprocessors import OListProcessor, UListProcessor
 import re
--- markdown/extensions/smart_strong.py
+++ markdown/extensions/smart_strong.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 '''
 Smart_Strong Extension for Python-Markdown
 ==========================================
@@ -24,6 +23,7 @@ Copyright 2011
 '''

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..inlinepatterns import SimpleTagPattern

--- markdown/extensions/tables.py
+++ markdown/extensions/tables.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Tables Extension for Python-Markdown
 ====================================
@@ -16,6 +15,7 @@ Copyright 2009 - [Waylan Limberg](http://achinghead.com)
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..blockprocessors import BlockProcessor
 from ..util import etree
--- markdown/extensions/toc.py
+++ markdown/extensions/toc.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 Table of Contents Extension for Python-Markdown
 * * *
@@ -11,6 +10,7 @@ Dependencies:
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..treeprocessors import Treeprocessor
 from ..util import etree
--- markdown/extensions/wikilinks.py
+++ markdown/extensions/wikilinks.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 '''
 WikiLinks Extension for Python-Markdown
 ======================================
@@ -78,6 +77,7 @@ Dependencies:
 '''

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import Extension
 from ..inlinepatterns import Pattern
 from ..util import etree
--- markdown/inlinepatterns.py
+++ markdown/inlinepatterns.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 INLINE PATTERNS
 =============================================================================
@@ -43,6 +42,7 @@ So, we apply the expressions in the following order:
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import util
 from . import odict
 import re
--- markdown/postprocessors.py
+++ markdown/postprocessors.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 POST-PROCESSORS
 =============================================================================
@@ -10,6 +9,7 @@ processing.
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import util
 from . import odict
 import re
--- markdown/preprocessors.py
+++ markdown/preprocessors.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 """
 PRE-PROCESSORS
 =============================================================================
@@ -8,6 +7,7 @@ complicated.
 """

 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import util
 from . import odict
 import re
--- markdown/serializers.py
+++ markdown/serializers.py
@@ -1,4 +1,3 @@
-from __future__ import unicode_literals
 # markdown/searializers.py
 #
 # Add x/html serialization to Elementree
@@ -39,6 +38,7 @@ from __future__ import unicode_literals


 from __future__ import absolute_import
+from __future__ import unicode_literals
 from . import util
 ElementTree = util.etree.ElementTree
 QName = util.etree.QName
```

**Comment by mitya57** [comment]
Docstrings [**can** be used](http://docs.python.org/3/reference/simple_stmts.html#future-statements) before `__future__` imports. Other literals can't, but in your case it is a docstring, so this actually looks like a bug in Jython (this doesn't mean we shouldn't work it around, though).

**Comment by me-and** [comment]
The `__init__.py` case shows what looks like a docstring, but before the suggested patch isn't, due to having a `from __future__ import` statement preceeding it. At a quick glance, the other files seem the same. 

As such, I think this is a genuine bug in Python Markdown, which wasn't noticed due to the CPython bug the OP linked to.

**Comment by Arfrever** [comment]
CPython bug has been fixed, but only in CPython 3.4. Markdown needs to be fixed for compatibility with at least CPython 3.4.

**Comment by waylan** [comment]
Sorry, but I'm confused. The [docs](http://docs.python.org/3/reference/simple_stmts.html#future-statements) state:

> A future statement must appear near the top of the module. The only lines that can appear before a future statement are:
> - the module docstring (if any),
> - comments,
> - blank lines, and
> - other future statements.

All of the future statements in Python-Markdown follow that rule. It would seem to me that if non-C python implementations did not work, that is a bug in that Python implementation. That said, if all we need to do is move the future statements before any module docstring and/or comments, then that's easy enough to do.

However, it should be noted that Python-Markdown 2.3 only officially supports CPython. Sure I would like to support other Pythons, but don't currently have them installed on my system for testing. Pypy should be easy enough (and will probably be added soon), but the dependencies for the others are more of an obstacle.

**Comment by me-and** [comment]
@waylan: As per the OP's patch, there are a number of future statements that don't follow that rule. For example in 2.3.final:markdown/__init__.py, line 1 is a future statement (added at 579288c5), which means the string literal starting at line 2 is no longer a docstring but just a regular string literal, and then there's another future statement added in the same commit at line 34.
