### ISSUE TITLE
Test error with Python 2.6

### ISSUE THREAD

**Issue by Arfrever** [Python-Markdown/markdown#294]
Markdown test suite has 1 error with Python 2.6
`assertIs` was introduced in Python 2.7 and 3.1.

```
$ PYTHONPATH=build/lib nosetests-2.6
.............................................................................................S.........................SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS............................E...........................................................................
======================================================================
ERROR: testBooleansParsing (tests.test_apis.TestConfigParsing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/Python-Markdown/tests/test_apis.py", line 428, in testBooleansParsing
    self.assertParses(True, True)
  File "/tmp/Python-Markdown/tests/test_apis.py", line 425, in assertParses
    self.assertIs(markdown.util.parseBoolValue(value, False), result)
AttributeError: 'TestConfigParsing' object has no attribute 'assertIs'

----------------------------------------------------------------------
Ran 298 tests in 4.010s

FAILED (SKIP=76, errors=1)
```

**Comment by Arfrever** [comment]
```
--- tests/test_apis.py
+++ tests/test_apis.py
@@ -422,7 +422,7 @@

 class TestConfigParsing(unittest.TestCase):
     def assertParses(self, value, result):
-        self.assertIs(markdown.util.parseBoolValue(value, False), result)
+        self.assertTrue(markdown.util.parseBoolValue(value, False) is result)

     def testBooleansParsing(self):
         self.assertParses(True, True)
```
