### ISSUE TITLE
markdown 2.5 not installable on python2.6

### ISSUE THREAD

**Issue by bukzor** [Python-Markdown/markdown#349]
`pip install 'markdown<2.5'` works fine however.

Apparently logging.captureWarnings was new in 2.7.

``` bash
$ pip install markdown -I
Downloading/unpacking markdown
  Using cached Markdown-2.5.tar.gz
  Running setup.py (path:/nail/home/buck/pg/2/virtualenv_run/build/markdown/setup.py) egg_info for package markdown
Installing collected packages: markdown
  Running setup.py install for markdown
    changing mode of build/scripts-2.6/markdown_py from 644 to 755
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/nail/home/buck/pg/2/virtualenv_run/build/markdown/setup.py", line 249, in <module>
        'Topic :: Text Processing :: Markup :: HTML',
      File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/nail/home/buck/pg/2/virtualenv_run/lib/python2.6/site-packages/setuptools/command/install.py", line 59, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.6/distutils/command/install.py", line 615, in run
        self.run_command('build')
      File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
        cmd_obj.run()
      File "/nail/home/buck/pg/2/virtualenv_run/build/markdown/setup.py", line 141, in run
        import markdown
      File "build/lib.linux-x86_64-2.6/markdown/__init__.py", line 53, in <module>
        logging.captureWarnings(True)
    AttributeError: 'module' object has no attribute 'captureWarnings'
```

**Comment by waylan** [comment]
As the [release notes](https://pythonhosted.org/Markdown/release-2.5.html#backwards-incompatible-changes) clearly state:

> Python-Markdown no longer supports Python version 2.6. You must be using Python versions 2.7, 3.2, 3.3, or 3.4.

As this is not a bug, I am closing this.

**Comment by bukzor** [comment]
We're still using python2.6 in production.
Would you accept a patch that re-adds python2.6 support, and CI for it?

**Comment by waylan** [comment]
@bukzor please see my comments on #344. I will not be supporting Python 2.6 going forward.
