### ISSUE TITLE
setConfigs doesn't handle None in __init__.py

### ISSUE THREAD

**Issue by gsingers** [Python-Markdown/markdown#357]
In `__init__.py`, line 75 or so, the for loop there doesn't check to see if the items dict is empty or not.  This causes a problem in the Apache CMS extension that relies on this code.   Resulting error is: 

``` python
Traceback (most recent call last):
  File "markdownd.py", line 42, in <module>
    dummy = markdown.markdown(unicode("", "utf-8"), EXTENSIONS)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/markdown/__init__.py", line 464, in markdown
    md = Markdown(*args, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/markdown/__init__.py", line 154, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/markdown/__init__.py", line 180, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/markdown/__init__.py", line 265, in build_extension
    return module.makeExtension(**configs)
  File ".../lucene/cms/asf-cms/mdx_elementid.py", line 150, in makeExtension
    return IdExtension(configs=configs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 36, in __init__
    self.setConfigs(kwargs.pop('configs', {}))
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 76, in setConfigs
    for key, value in items:
TypeError: 'NoneType' object is not iterable
```

Wrapping in an if fixes the issue:

``` python
        if (items):
            for key, value in items:
                self.setConfig(key, value)
```

**Comment by waylan** [comment]
I assume you mean `setConfigs` (with an s) not `SetConfig`, `None` not `null` and "dictionary" not "array."  I've edited your post to correct those errors -- and marked the code as code so it displays correctly.

As `setConfigs` is a new method, I don't see why this is a problem. It has been documented as only accepting a dictionary since its introduction. Why should one expect it to accept `None`. I didn't look, but if Apache CMS extension was implementing its own `setConfigs` method before we ever had one, then it can either change to match the newly created API or continue to implement its own method. If, on the other hand, there is a real world advantage to it accepting `None` values I might reconsider. But 'extension X has implemented its own non-standard API' is not a reason in itself.

**Comment by waylan** [comment]
So I just read through the Traceback (now that it is formated -- and readable) and I don't see how `items` could ever be `None`, unless somewhere in the extension a method/function is defining its `configs` keyword as `configs=None` (eg: `def some_funct(configs=None):`). If that is what it is doing, that is not considered good practice. I realize it **may** have worked before, but that was only by accident. In fact, as pointed out in the [release notes](https://pythonhosted.org/Markdown/release-2.5.html), the `configs` keyword is being deprecated (among other things), in which case the extension needs to be updated anyway. When I updated the extension configs stuff, I realized this may break some extensions that weren't following current best practices (for example we've discouraged using the `mdx_*` naming scheme for years now, which is still used by the extension in question). I offer no apologies about that. Those extension authors need to update their extensions.

**Comment by gsingers** [comment]
That was indeed how it was passed in.  BTW, I'm just the messenger here.  I didn't write the extension, I'm just stuck using it and the way I fixed the issue was by checking for None in the above file.  I will reach out to the extension authors.
