### ISSUE TITLE
Some tests fail with Pygments 2.0rc1

### ISSUE THREAD

**Issue by mitya57** [Python-Markdown/markdown#361]
[Pygments 2.0rc1](https://bitbucket.org/birkenfeld/pygments-main/commits/tag/2.0rc1) was released recently, and our tests are now failing with it.

```
======================================================================
FAIL: testBasicCodeHilite (tests.test_extensions.TestCodeHilite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/python-markdown-2.5.1/tests/test_extensions.py", line 95, in testBasicCodeHilite
    '<div class="codehilite">'
AssertionError: u'<div class="codehilite"><pre># A Code Comment\n</pre></div>' != u'<div class="codehilite"><pre><span class="c"># A Code Comment</span>\n</pre></ [truncated]...
- <div class="codehilite"><pre># A Code Comment
+ <div class="codehilite"><pre><span class="c"># A Code Comment</span>
?                              ++++++++++++++++                +++++++
  </pre></div>
-------------------- >> begin captured logging << --------------------
MARKDOWN: DEBUG: Successfuly imported extension module "markdown.extensions.codehilite".
MARKDOWN: INFO: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: testLinenumsNone (tests.test_extensions.TestCodeHilite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/buildd/python-markdown-2.5.1/tests/test_extensions.py", line 138, in testLinenumsNone
    '<div class="codehilite">'
AssertionError: u'<div class="codehilite"><pre># A Code Comment\n</pre></div>' != u'<div class="codehilite"><pre><span class="c"># A Code Comment</span>\n</pre></ [truncated]...
- <div class="codehilite"><pre># A Code Comment
+ <div class="codehilite"><pre><span class="c"># A Code Comment</span>
?                              ++++++++++++++++                +++++++
  </pre></div>
-------------------- >> begin captured logging << --------------------
MARKDOWN: INFO: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
--------------------- >> end captured logging << ---------------------
```

Their `withColon` analogues still work, so it looks like the code without a colon line or shebang is no longer recognized as Python code.

I think we should just drop these two tests, what do you think?

**Comment by mitya57** [comment]
Some more debugging: with old Pygments I get:

``` py3console
>>> from pygments.lexers import guess_lexer
>>> guess_lexer('# A code comment')
<pygments.lexers.SourcesListLexer>
```

With new Pygments I get:

``` py3console
>>> from pygments.lexers import guess_lexer
>>> guess_lexer('# A code comment')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pygments/lexers/__init__.py", line 250, in guess_lexer
    raise ClassNotFound('no lexer matching the text found')
pygments.util.ClassNotFound: no lexer matching the text found
```

So this is probably a result of [this commit](https://bitbucket.org/birkenfeld/pygments-main/commits/cac33c1aeee113f40880903fdd3a93fcdfc55b1b), which looks like an intentional change.

**Comment by waylan** [comment]
Groan. I think we should do what we have done on a few other tests. See [this comment](https://github.com/waylan/Python-Markdown/blob/master/tests/test_extensions.py#L108) for example. Using `startswith('<div class="codehilite"><pre>')` should be enough to confirm that pygments ran properly without line numbering in those two tests. That way we get to keep the tests (maintaining good test coverage) and the tests will still pass with different versions of Pygments.

What is more concerning is that some users will complain that their code used to get highlighted and now it doesn't -- which is completely out of our control. This just stresses the importance of not relying on language autodetection. If you want highlighting, you should define the language specifically. At least we have it documented here to point people to. Thanks for the report.
