### ISSUE TITLE
markdown 2.6.5 install error

### ISSUE THREAD

**Issue by rabinutam** [Python-Markdown/markdown#448]
install markdown version <=2.4.1 is successful, 
install markdown version >2.4.1 is not

python version: 2.6.6
OS: Linux, 2.6.32-504.16.2.el6.x86_64

While trying to
$ pip install markdown
or (dowload Markdown-2.6.5.tar.gz, and install)

I am getting following error:
...
creating build/docs
copying docs/py.png -> build/docs
copying docs/release-2.4.txt -> build/docs
Converting docs/release-2.4.txt -> build/docs/release-2.4.html
Traceback (most recent call last):
  File "setup.py", line 270, in <module>
    'Topic :: Text Processing :: Markup :: HTML'
  File "/usr/lib64/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.6/distutils/command/install.py", line 577, in run
    self.run_command('build')
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.6/distutils/command/build.py", line 134, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "setup.py", line 184, in run
    out = template % self._get_context(src, outfile)
  File "setup.py", line 116, in _get_context
    c['body'] = self.md.convert(src)
  File "build/lib/markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "build/lib/markdown/extensions/toc.py", line 228, in run
    for el in doc.iter():
AttributeError: iter

**Comment by waylan** [comment]
As of [version 2.5](https://pythonhosted.org/Markdown/release-2.5.html), Python-Markdown no longer supports Python 2.6 (see [an explanation](https://github.com/waylan/Python-Markdown/pull/344#issuecomment-56591935)). In fact, our current release is now [version 2.6](https://pythonhosted.org/Markdown/release-2.6.html). As this library is developed by volunteers in our spare time, no support is provided for older versions of the library. As such, this issue is being closed.
