### ISSUE TITLE
attr_list extension bug - ValueError: too many values to unpack

### ISSUE THREAD

**Issue by ezarowny** [Python-Markdown/markdown#498]
With the attr_list extension on, If I feed the following text into markdown:

``` python
text = """{"path":"/messages","ref":"https://host.tld/break_markdown/new?some_id=INT&layout=iframe&receiver_id=INT"}
{"path":"/messages/new?some_id=INT&layout=iframe&receiver_id=INT","ref":"-"}"""
```

with the following function:

``` python
extensions = [
    'markdown.extensions.fenced_code',
    'markdown.extensions.attr_list',
    'markdown.extensions.def_list',
    'codehilite(css_class=highlight)',
]

print markdown(text, safe_mode='escape', output_format='html', extensions=extensions)
```

I get an error:

```
ValueError                                Traceback (most recent call last)
<ipython-input-9-81fe27f05c8e> in <module>()
----> 1 markdown.markdown(text_2, safe_mode='escape', output_format='html', extensions=extensions)

/home/vagrant/.virtualenvs/moxenv/local/lib/python2.7/site-packages/markdown/__init__.pyc in markdown(text, *args, **kwargs)
    492     """
    493     md = Markdown(*args, **kwargs)
--> 494     return md.convert(text)
    495
    496

/home/vagrant/.virtualenvs/moxenv/local/lib/python2.7/site-packages/markdown/__init__.pyc in convert(self, source)
    373         # Run the tree-processors
    374         for treeprocessor in self.treeprocessors.values():
--> 375             newRoot = treeprocessor.run(root)
    376             if newRoot is not None:
    377                 root = newRoot

/home/vagrant/.virtualenvs/moxenv/local/lib/python2.7/site-packages/markdown/extensions/attr_list.pyc in run(self, doc)
    132                         m = re.search(self.BASE_RE, elem.text)
    133                     if m:
--> 134                         self.assign_attrs(elem, m.group(1))
    135                         elem.text = elem.text[:m.start()]
    136                         if isheader(elem):

/home/vagrant/.virtualenvs/moxenv/local/lib/python2.7/site-packages/markdown/extensions/attr_list.pyc in assign_attrs(self, elem, attrs)
    147     def assign_attrs(self, elem, attrs):
    148         """ Assign attrs to element. """
--> 149         for k, v in get_attrs(attrs):
    150             if k == '.':
    151                 # add to class

ValueError: too many values to unpack
```

**Comment by waylan** [comment]
Thanks for the report. There is a lot of extra unrelevant stuff in there. Let's distill that down to the simplest possible reproduction of the error:

``` python
>>> t = 'paragraph\n{bar=blah=baz}'
>>> markdown.markdown(t, extensions=['markdown.extensions.attr_list'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "markdown/__init__.py", line 494, in markdown
    return md.convert(text)
  File "markdown/__init__.py", line 375, in convert
    newRoot = treeprocessor.run(root)
  File "markdown/extensions/attr_list.py", line 134, in run
    self.assign_attrs(elem, m.group(1))
  File "markdown/extensions/attr_list.py", line 149, in assign_attrs
    for k, v in get_attrs(attrs):
ValueError: too many values to unpack
```

Clearly this is a failure of the attr_list parser when a single item contains three `=` characters.
