### ISSUE TITLE
Fix for Python 3.6

### ISSUE THREAD

**Issue by brandonchinn178** [Python-Markdown/markdown#499]
I'm trying to upgrade my project to Python 3.6 so that, even though it's in beta, when it does get released to its full version, it'll be a simple pull request to update python versions. But currently, installing Markdown gives me:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hiv4fz31/Markdown/setup.py", line 270, in <module>
        'Topic :: Text Processing :: Markup :: HTML'
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-hiv4fz31/Markdown/setup.py", line 184, in run
        out = template % self._get_context(src, outfile)
      File "/tmp/pip-build-hiv4fz31/Markdown/setup.py", line 116, in _get_context
        c['body'] = self.md.convert(src)
      File "build/lib/markdown/__init__.py", line 375, in convert
        newRoot = treeprocessor.run(root)
      File "build/lib/markdown/treeprocessors.py", line 361, in run
        brs = root.getiterator('br')
    SystemError: Python/getargs.c:1508: bad argument to internal function
```

Is there a quick fix to this solution already, or is this a new bug with 3.6?

**Comment by brandonchinn178** [comment]
Note: tested the following:

```
# python 2.7
>>> Element('div').getiterator() # returns [<Element 'div'>]
>>> Element('div').getiterator('div') # returns [<Element 'div'>]
>>> Element('div').getiterator('br') # return []

# python 3.4.3
>>> Element('div').getiterator() # returns [<Element 'div'>]
>>> Element('div').getiterator('div') # returns [<Element 'div'>]
>>> Element('div').getiterator('br') # return []

# python 3.6
>>> Element('div').getiterator() # returns [<Element 'div'>]
>>> Element('div').getiterator('div') # errors "'div' is an invalid keyword argument for this function"
>>> Element('div').getiterator('br') # return "'br' is an invalid keyword argument for this function"
```
