### ISSUE TITLE
Install fails on Python 3.6 with 'br' is invalid keyword argument

### ISSUE THREAD

**Issue by jaraco** [Python-Markdown/markdown#502]
Attempting to install latest markdown on Python 3.6.0b1 fails with this error:

```
$ python -m pip install -t foo markdown
Collecting markdown
  Using cached Markdown-2.6.7.zip
Installing collected packages: markdown
  Running setup.py install for markdown ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-build-3fubfbqm/markdown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-kwhawl52-record/install-record.txt --single-version-externally-managed --compile --home=/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/tmpowua21z4:
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/markdown
    copying markdown/__init__.py -> build/lib/markdown
    copying markdown/__main__.py -> build/lib/markdown
    copying markdown/__version__.py -> build/lib/markdown
    copying markdown/blockparser.py -> build/lib/markdown
    copying markdown/blockprocessors.py -> build/lib/markdown
    copying markdown/inlinepatterns.py -> build/lib/markdown
    copying markdown/odict.py -> build/lib/markdown
    copying markdown/postprocessors.py -> build/lib/markdown
    copying markdown/preprocessors.py -> build/lib/markdown
    copying markdown/serializers.py -> build/lib/markdown
    copying markdown/treeprocessors.py -> build/lib/markdown
    copying markdown/util.py -> build/lib/markdown
    creating build/lib/markdown/extensions
    copying markdown/extensions/__init__.py -> build/lib/markdown/extensions
    copying markdown/extensions/abbr.py -> build/lib/markdown/extensions
    copying markdown/extensions/admonition.py -> build/lib/markdown/extensions
    copying markdown/extensions/attr_list.py -> build/lib/markdown/extensions
    copying markdown/extensions/codehilite.py -> build/lib/markdown/extensions
    copying markdown/extensions/def_list.py -> build/lib/markdown/extensions
    copying markdown/extensions/extra.py -> build/lib/markdown/extensions
    copying markdown/extensions/fenced_code.py -> build/lib/markdown/extensions
    copying markdown/extensions/footnotes.py -> build/lib/markdown/extensions
    copying markdown/extensions/headerid.py -> build/lib/markdown/extensions
    copying markdown/extensions/meta.py -> build/lib/markdown/extensions
    copying markdown/extensions/nl2br.py -> build/lib/markdown/extensions
    copying markdown/extensions/sane_lists.py -> build/lib/markdown/extensions
    copying markdown/extensions/smart_strong.py -> build/lib/markdown/extensions
    copying markdown/extensions/smarty.py -> build/lib/markdown/extensions
    copying markdown/extensions/tables.py -> build/lib/markdown/extensions
    copying markdown/extensions/toc.py -> build/lib/markdown/extensions
    copying markdown/extensions/wikilinks.py -> build/lib/markdown/extensions
    running build_scripts
    creating build/scripts-3.6
    copying and adjusting bin/markdown_py -> build/scripts-3.6
    changing mode of build/scripts-3.6/markdown_py from 644 to 755
    running build_docs
    creating build/docs
    copying docs/authors.txt -> build/docs
    Converting docs/authors.txt -> build/docs/authors.html
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-build-3fubfbqm/markdown/setup.py", line 270, in <module>
        'Topic :: Text Processing :: Markup :: HTML'
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-build-3fubfbqm/markdown/setup.py", line 184, in run
        out = template % self._get_context(src, outfile)
      File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-build-3fubfbqm/markdown/setup.py", line 116, in _get_context
        c['body'] = self.md.convert(src)
      File "build/lib/markdown/__init__.py", line 375, in convert
        newRoot = treeprocessor.run(root)
      File "build/lib/markdown/treeprocessors.py", line 361, in run
        brs = root.getiterator('br')
    TypeError: 'br' is an invalid keyword argument for this function

    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-build-3fubfbqm/markdown/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-kwhawl52-record/install-record.txt --single-version-externally-managed --compile --home=/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/tmpowua21z4" failed with error code 1 in /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-build-3fubfbqm/markdown/
```

**Comment by mitya57** [comment]
This is a [bug](http://bugs.python.org/issue28314) in Python 3.6 (already fixed upstream). A workaround is also in the latest Python-Markdown Git. See #499 and #500 for details.

**Comment by jaraco** [comment]
Excellent. Thanks!
