### ISSUE TITLE
Traceback when using cmdline tool with Python 3.2

### ISSUE THREAD

**Issue by thmo** [Python-Markdown/markdown#61]
Built and installed markdown 2.1.0 using Python 3.2.1, on Fedora 16 (markdown_py has been renamed to /usr/bin/markdown_py-3.2).

Now:

```
% /bin/echo -e "### Heading\n\ntest" | markdown_py-3.2
Traceback (most recent call last):
  File "/usr/bin/markdown_py-3.2", line 34, in <module>
    run()
  File "/usr/lib/python3.2/site-packages/markdown/__main__.py", line 81, in run
    markdown.markdownFromFile(**options)
  File "/usr/lib/python3.2/site-packages/markdown/__init__.py", line 416, in markdownFromFile
    kwargs.get('encoding', None))
  File "/usr/lib/python3.2/site-packages/markdown/__init__.py", line 341, in convertFile
    text = input_file.read()
  File "/usr/lib64/python3.2/codecs.py", line 480, in read
    data = self.bytebuffer + newdata
TypeError: can't concat bytes to str
```

Specifying -e UTF-8 does not help.

**Comment by waylan** [comment]
Hmm, what happens if you use python's -m flag?

```
/bin/echo -e "### Heading\n\ntest" | python -m markdown
```

We just added support for that and I'm wondering if it gives the same behavior.

Also, do you get the same behavior when reading from a file rather than stdin?

**Comment by thmo** [comment]
The problem remains when using the -m flag, and also when using a file instead of stdin, albeit in the latter case with a different traceback:

```
% /bin/echo -e "### Heading\n\ntest" > test.md
% markdown_py-3.2 test.md  
Traceback (most recent call last):
  File "/usr/bin/markdown_py-3.2", line 34, in <module>
    run()
  File "/usr/lib/python3.2/site-packages/markdown/__main__.py", line 81, in run
    markdown.markdownFromFile(**options)
  File "/usr/lib/python3.2/site-packages/markdown/__init__.py", line 416, in markdownFromFile
    kwargs.get('encoding', None))
  File "/usr/lib/python3.2/site-packages/markdown/__init__.py", line 357, in convertFile
    output.write(html.encode(encoding, "xmlcharrefreplace"))
TypeError: must be str, not bytes
```
