### ISSUE TITLE
Does it support Chinese?

### ISSUE THREAD

**Issue by BarryRun** [Python-Markdown/markdown#680]
Just like this:
Traceback (most recent call last):
  File "C:\Users\w84107210\AppData\Local\Programs\Python\Python37\Scripts\markdown_py", line 34, in <module>
    run()
  File "...\Python\Python37\lib\site-packages\markdown\__main__.py", line 81, in run
    markdown.markdownFromFile(**options)
  File ...\Python\Python37\lib\site-packages\markdown\__init__.py", line 442, in markdownFromFile
    kwargs.get('encoding', None))
  File "...\Python\Python37\lib\site-packages\markdown\__init__.py", line 350, in convertFile
    text = input_file.read()
  File "...\Python\Python37\lib\codecs.py", line 701, in read
    return self.reader.read(size)
  File "...\Python\Python37\lib\codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 3: invalid start byte

**Comment by waylan** [comment]
Have you confirmed that the file is encoded as "UTF-8"? Also be sure the file does not contain a [byte order mark][1]. If those two things are true, then there should be no reason it doesn't work.

[1]: https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by waylan** [comment]
Due to the lack of feedback and an inability to reproduce the error, it is assumed this was user error. Therefore I'm closing this.
