### ISSUE TITLE
Support Tor-traffic

### ISSUE THREAD

**Issue by GammaSQ** [Python-Markdown/markdown#682]
Or rather, don't block Tor!
This command works as expected without Tor (tested on fedora with optional whonix-proxy inserted), but throws an error when using the Tor network:

    $ nikola plugin -l
    Traceback (most recent call last):
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
        return command.parse_execute(args)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
        return self.execute(params, args)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/nikola/plugin_categories.py", line 134, in execute
        return self._execute(options, args)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/nikola/plugins/command/plugin.py", line 149, in _execute
        return self.list_available(url)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/nikola/plugins/command/plugin.py", line 161, in list_available
        data = self.get_json(url)
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/nikola/plugins/command/plugin.py", line 354, in get_json
        self.json = requests.get(url).json()
      File "/home/user/Documents/projects/rocketcollider/venv/lib64/python3.6/site-packages/requests/models.py", line 896, in json
        return complexjson.loads(self.text, **kwargs)
      File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by waylan** [comment]
It would appear that you have reported this to the wrong project. I see no reference to Python-Markdown being called in your traceback. And I have no idea what `nikola` is.

**Comment by GammaSQ** [comment]
Yes, sry, had Nikola-tab open paraallel, my bad.
