### ISSUE TITLE
crash on URLs with square brackets

### ISSUE THREAD

**Issue by aaronsw** [Python-Markdown/markdown#69]
It's not a great URL, but markdown shouldn't crash on it:

```
>>> markdown.markdown('[x](http://example.com])')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/__init__.py", line 386, in markdown
    return md.convert(text)
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/__init__.py", line 287, in convert
    newRoot = treeprocessor.run(root)
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/treeprocessors.py", line 289, in run
    text), child)
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/treeprocessors.py", line 110, in __handleInline
    data, patternIndex, startIndex)
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/treeprocessors.py", line 237, in __applyPattern
    node = pattern.handleMatch(match)
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/inlinepatterns.py", line 288, in handleMatch
    el.set("href", self.sanitize_url(self.unescape(href.strip())))
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/inlinepatterns.py", line 315, in sanitize_url
    scheme, netloc, path, params, query, fragment = url = urlparse(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 134, in urlparse
    tuple = urlsplit(url, scheme, allow_fragments)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 182, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```

**Comment by waylan** [comment]
At first I found it strange that the error message was mentioning "IPv6" urls. Then I noticed that this error only occurs in Python 2.7+. A quick look at the [docs](http://docs.python.org/library/urlparse.html#urlparse.urlparse) confirms that IPv6 parsing support was added in Python 2.7 to the urlparse module. Apparently, adding a square bracket to the end of a url causes urlparse to think it is an invalid IPv6 url. No sure how to work around that.
