### ISSUE TITLE
RawHTML crashes on empty anglebrackets

### ISSUE THREAD

**Issue by aaronsw** [Python-Markdown/markdown#70]
This definitely shouldn't cause a crash:

```
>>> markdown.markdown('<>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/__init__.py", line 386, in markdown
    return md.convert(text)
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/__init__.py", line 280, in convert
    self.lines = prep.run(self.lines)
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/preprocessors.py", line 146, in run
    left_tag, left_index, attrs = self._get_left_tag(block)
  File "/Users/aaronsw/Code/infohacks/jottit/code/env/lib/python2.7/site-packages/markdown/preprocessors.py", line 81, in _get_left_tag
    tag = block[1:].replace(">", " ", 1).split()[0].lower()
IndexError: list index out of range
```

**Comment by waylan** [comment]
Changed title to better reflect problem. This is related to rawhtml not urls.
