### ISSUE TITLE
Command Line Script does not write to stdout on Windows Python 3.2

### ISSUE THREAD

**Issue by DarkLinkXXXX** [Python-Markdown/markdown#79]
C:\Users\Alex\test>markdown_py test.txt
Traceback (most recent call last):
  File "C:\Users\Alex\python32\Scripts\markdown_py", line 34, in <module>
    run()
  File "C:\Users\Alex\python32\lib\site-packages\markdown__main__.py", line 81,
 in run
    markdown.markdownFromFile(**options)
  File "C:\Users\Alex\python32\lib\site-packages\markdown__init__.py", line 426
, in markdownFromFile
    kwargs.get('encoding', None))
  File "C:\Users\Alex\python32\lib\site-packages\markdown__init__.py", line 364
, in convertFile
    output_file.write(html)
  File "C:\Users\Alex\python32\lib\codecs.py", line 356, in write
    self.stream.write(data)
TypeError: must be str, not bytes

**Comment by waylan** [comment]
Well, it works fine on Windows Python 3.2 as a python library (we are a lib first & script second). However, yes, it appears that there is a bug in the command line wrapper script. I've changed the title to better reflect the problem. Thanks for the report.
