### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by p-ouellette** [Python-Markdown/markdown#791]
I tried installing with `pip install git+https://github.com/Python-Markdown/markdown.git` inside a virtualenv. Output:
```
Collecting git+https://github.com/Python-Markdown/markdown.git
  Cloning https://github.com/Python-Markdown/markdown.git to /tmp/pip-req-build-o9_0att9
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /home/paul/venv/bin/python3 /home/paul/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp8vj_j3z6:
  Traceback (most recent call last):
    File "/home/paul/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/paul/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/paul/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-ljq_sr2i/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-ljq_sr2i/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ljq_sr2i/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 26, in <module>
      from markdown import __version__, __version_info__
  ModuleNotFoundError: No module named 'markdown'
  
  ----------------------------------------
Command "/home/paul/venv/bin/python3 /home/paul/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp8vj_j3z6" failed with error code 1 in /tmp/pip-req-build-o9_0att9
```
The same thing happens on the GitLab CI. It worked 3 weeks ago.

**Comment by waylan** [comment]
We have made no changes to anything related to installation. In fact, we only made three commits in the last three weeks. I have no idea what could be causing this. My assumption is that the problem is related to your environment. Did you perhaps change pip versions or something?

**Comment by p-ouellette** [comment]
It's a pip thing. It works on GitLab CI with pip 18.1, but not the recently released 19.0.2.

**Comment by waylan** [comment]
I just read through pip's [release notes][1] and nothing jumps out at me. Although, in version 19.0, pip fully adopts PEP 517. I'm assuming that broke this. What it not clear is if that breakage was intentional or not. We probably need to open an issue at [pypa/pip](https://github.com/pypa/pip).

[1]: https://pip.pypa.io/en/stable/news/

**Comment by waylan** [comment]
I'm closing this as a duplicate of #823. I realize this was opened first, but that better identifies the problem and already includes a discussion of possible solutions.
