### ISSUE TITLE
AttributeError: module 'copy' has no attribute 'copy'

### ISSUE THREAD

**Issue by ahmetanbar** [Python-Markdown/markdown#853]
Hi, 

The `deneme.py` file is just

> import markdown

When I run this file, I get the following errors. 

> Traceback (most recent call last):
  File "C:/Users/ahmetanbar/Desktop/deneme.py", line 1, in <module>
    import markdown
  File "C:\Program Files\Python37\lib\site-packages\markdown\__init__.py", line 25, in <module>
    from .core import Markdown, markdown, markdownFromFile
  File "C:\Program Files\Python37\lib\site-packages\markdown\core.py", line 29, in <module>
    import pkg_resources
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\__init__.py", line 84, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
    __import__(extant)
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 4761, in <module>
    _reBracketExpr = Literal("[") + Optional("^").setResultsName("negate") + Group( OneOrMore( _charRange | _singleChar ) ).setResultsName("body") + "]"
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1224, in setResultsName
    newself = self.copy()
  File "C:\Program Files\Python37\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1183, in copy
    cpy = copy.copy( self )
AttributeError: module 'copy' has no attribute 'copy'

My env:
Python 3.7
Windows 10 
PyCharm 

I also try to run on terminal, but I got the same result.

**Comment by ahmetanbar** [comment]
Solved. Don't have a file with name `copy.py` on the same directory.
